config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
root 'products#index'
resources :products
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

def index
  @products = Product.all
end

  def new
    @product = Product.new
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/herbs_helper.rb
module HerbsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/herbs/index.html.erb
<h1>Welcome to my Awesome Web App</h1>

app/views/herbs/new.html.erb
<div class="booyah-box col-10 offset-1">
  <h1>Enter Your Place Details</h1>
  <%= simple_form_for @place do |f| %>
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :description %>
    <br />
    <%= f.submit 'Create', class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Herbify</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <nav class="navbar navbar-toggleable-md navbar-inverse bg-inverse">
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <%= link_to 'Herbify', root_path, class: 'navbar-brand' %>

  <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
    <ul class="navbar-nav mr-auto mt-2 mt-md-0">
      <li class="nav-item">
       <%= link_to 'Products', new_product_path, class: 'navbar-brand' %> 
      </li>
    </ul>
  </div>
</nav>

  <body>
    <%= yield %>
  </body>
  <h1>Welcome to Herbify!</h1>
  <p> A platform where we discuss different herbs and their benefits, how you liked them +more! </p>
</html>

app/views/products/index.html.erb
<% @products.each do |product| %>
  <div>
    <h1><%= product.name %></h1><br />
    <p><%= product.description %></p><br />
  </div>

  <hr />
<% end %>

app/views/products/new.html.erb
<div class="booyah-box col-10 offset-1">
  <h1>Enter Your Product Details</h1>
    <%= simple_form_for @product do |f| %>
    <%= f.input :name %>
    <%= f.input :description %>
    <br />
    <%= f.submit 'Create', class: 'btn btn-primary' %>
 
    

  <% end %>
</div>